/*
 * idt.h - Interrupt Descriptor Table
 *
 * WHAT ARE INTERRUPTS?
 *
 * An interrupt temporarily pauses normal execution to handle an event.
 * There are three kinds in x86:
 *
 * 1. CPU EXCEPTIONS (vectors 0–31): errors or special conditions
 *    generated by the CPU itself.
 *    Examples:
 *      #DE (0)  = Division by Zero
 *      #PF (14) = Page Fault (invalid memory access)
 *      #GP (13) = General Protection Fault (privilege violation)
 *
 * 2. HARDWARE INTERRUPTS / IRQs (vectors 32–47 in our setup):
 *    Signals from external hardware, routed through the PIC.
 *    Examples:
 *      IRQ0 (32) = PIT Timer (fires 100 times/second)
 *      IRQ1 (33) = PS/2 Keyboard (key was pressed/released)
 *
 * 3. SOFTWARE INTERRUPTS (INT instruction):
 *    Used for system calls (Linux uses INT 0x80) or BIOS calls in real mode.
 *
 * WHAT IS THE IDT?
 *
 * The IDT is an array of "gate descriptors". Each entry tells the CPU:
 *   - Which function (handler) to call for that interrupt vector number
 *   - What privilege level is required to trigger it via software
 *   - Whether to switch stacks, etc.
 *
 * The CPU loads the IDT address from the IDTR register (loaded with LIDT).
 *
 * HOW INTERRUPT HANDLING WORKS:
 *
 *   1. Interrupt fires (hardware or CPU)
 *   2. CPU saves current state to stack (EIP, CS, EFLAGS, optionally SS/ESP)
 *   3. CPU looks up the interrupt vector in the IDT
 *   4. CPU jumps to the handler function address from the IDT entry
 *   5. Handler runs, sends EOI to PIC (for hardware IRQs), returns with IRET
 *   6. CPU restores saved state and resumes normal execution
 */

#ifndef IDT_H
#define IDT_H

#include "kernel.h"

/*
 * IDT Entry (Gate Descriptor) — 8 bytes, hardware-defined
 *
 * x86 supports several gate types; we use "Interrupt Gates" (type=0xE)
 * which automatically disable interrupts (clear IF flag) on entry.
 *
 *  63       48 47 46-45 44 43-40 39-32 31       16 15       0
 *  ┌──────────┬──┬─────┬──┬─────┬─────┬──────────┬──────────┐
 *  │Offset[31:16]│P │ DPL │ 0 │Type │  000  │  Selector │Offset[15:0]│
 *  └──────────┴──┴─────┴──┴─────┴─────┴──────────┴──────────┘
 */
typedef struct {
    uint16_t offset_low;    /* Bits 0-15  of handler address */
    uint16_t selector;      /* Code segment selector (0x08 for kernel code) */
    uint8_t  zero;          /* Always 0  */

    /*
     * Type/Attribute byte:
     *   Bit 7: P   = Present (1 = valid entry)
     *   Bits 6-5: DPL = privilege level needed to trigger via INT instruction
     *   Bit 4: 0   = always 0 for interrupt/trap gates
     *   Bits 3-0: Type:
     *     0xE = 32-bit Interrupt Gate (disables interrupts on entry)
     *     0xF = 32-bit Trap Gate     (does NOT disable interrupts)
     *
     * For hardware IRQs and exceptions we use Interrupt Gates (0x8E):
     *   P=1, DPL=0, 0, type=0xE → 1000 1110 = 0x8E
     */
    uint8_t  type_attr;

    uint16_t offset_high;   /* Bits 16-31 of handler address */
} PACKED idt_entry_t;

/*
 * IDT Descriptor (IDTR register format) — same structure as GDTR
 */
typedef struct {
    uint16_t limit;   /* IDT size in bytes - 1 */
    uint32_t base;    /* Physical address of IDT array */
} PACKED idt_descriptor_t;

/* x86 supports 256 interrupt vectors (0–255) */
#define IDT_ENTRIES 256

/*
 * idt_init - Set up the IDT with all 256 entries and load it.
 *
 * Sets up:
 *   - 32 exception handlers (ISR 0–31)
 *   - 16 hardware IRQ handlers (IRQ 0–15, mapped to vectors 32–47)
 *   - Remaining entries point to a safe default handler
 */
void idt_init(void);

/*
 * idt_set_gate - Configure one IDT entry.
 *
 * @vector:   interrupt vector number (0–255)
 * @handler:  address of the assembly stub to call
 * @selector: code segment selector (use GDT_KERNEL_CODE = 0x08)
 * @type_attr: flags byte (use 0x8E for kernel interrupt gate)
 */
void idt_set_gate(uint8_t vector, uint32_t handler,
                  uint16_t selector, uint8_t type_attr);

#endif /* IDT_H */
